import { Project, Experience, Skill } from "@/lib/types";

export const PROJECTS: Project[] = [
  {
    id: "1",
    title: "Moury App",
    description:
      "A landing page for a cutting-edge with animations powered by Framer Motion  visualizations.",
    image: "./assets/moury.png",
    tags: ["Next.js", "Tailwind", "Framer Motion"],
    link: "https://www.mouryapp.com",
  },
  {
    id: "2",
    title: "Ethereal Commerce",
    description:
      "Minimalist headless commerce platform focused on high-conversion speed and fluidity.",
    image: "./assets/tinybee.png",
    tags: [
      "React.js",
      "Ant Design",
      "Framer Motion",
      "chart.js",
      "redux toolkit",
    ],
    link: "#",
  },
  {
    id: "3",
    title: "Zen Workspace",
    description:
      "A productivity suite with native-feeling animations and offline-first architecture.",
    image: "https://picsum.photos/seed/zen/1200/800",
    tags: ["TypeScript", "Tailwind", "Supabase"],
    link: "#",
  },
];

export const EXPERIENCES: Experience[] = [
  {
    company: "BizHub Consulting Service",
    role: "Front-End Engineer",
    period: "Jun 2024 – May 2025",
    location: "Ekantakuna, Lalitpur",
    bullets: [
      "Built production-grade admin panels, CRM dashboards, and client portals with Next.js, React, and TypeScript — delivered end-to-end features with SSR/ISR where required.",
      "Created a TypeScript-first, Storybook-driven component library and shared design tokens, reducing UI inconsistencies and speeding feature delivery.",
      "Implemented TanStack Query + Axios for cache-first fetching, background refetching and optimistic updates, cutting redundant API requests and improving UX responsiveness.",
      "Optimized rendering and bundle sizes using dynamic imports, route-level code-splitting, memoization, and selective hydration — noticeably improved initial load and interactivity.",
      "Leveraged Next.js image optimization and server-side rendering to boost SEO and first-contentful paint for marketing and client-facing pages.",
      "Translated Figma into pixel-accurate, accessible, and responsive interfaces; refined micro-interactions with designers to improve usability.",
      "Led frontend standards: TypeScript strict rules, linting, CI checks and code-review practices to maintain quality across multiple concurrent projects.",
    ],
  },
  {
    company: "Diyo.ai",
    role: "Front-End Developer",
    period: "Mar 2022 – Oct 2023",
    location: "Jwagal, Lalitpur",
    bullets: [
      "Developed and shipped customer-facing features and responsive landing pages using React and TypeScript, ensuring cross-device parity and accessibility.",
      "Refactored legacy UI into modular, typed hooks and reusable components—reduced duplication and regression risk while improving developer velocity.",
      "Integrated REST APIs with Axios and TanStack Query for cache-first fetching, cursor pagination, and consistent error handling across screens.",
      "Tracked down and fixed recurring UI bugs and performance hotspots, improving stability and reducing incident regressions between releases.",
      "Collaborated with designers and backend engineers to convert Figma prototypes into production-ready interfaces and align API contracts.",
      "Participated in Agile ceremonies (planning, estimation, retrospectives) and coordinated releases to meet tight deadlines.",
      "Established component naming conventions and review workflows that improved maintainability and onboarding speed for new engineers.",
    ],
  },
];

export const SKILLS: Skill[] = [
  {
    name: "React",
    category: "Frontend",
    years: 4,
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg",
    color: "#61DAFB",
    shadow: "rgba(97,218,251,.22)",
    glow: "rgba(97,218,251,.13)",
    accent: "#93e9ff",
    pillBg: "rgba(97,218,251,.12)",
    pillBorder: "rgba(97,218,251,.3)",
  },
  {
    name: "Next.js",
    category: "Frontend",
    years: 3,
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg",
    color: "rgba(255,255,255,.5)",
    shadow: "rgba(255,255,255,.12)",
    glow: "rgba(255,255,255,.08)",
    accent: "rgba(255,255,255,.7)",
    pillBg: "rgba(255,255,255,.07)",
    pillBorder: "rgba(255,255,255,.2)",
  },
  {
    name: "TypeScript",
    category: "Frontend",
    years: 3,
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg",
    color: "#3178C6",
    shadow: "rgba(49,120,198,.25)",
    glow: "rgba(49,120,198,.14)",
    accent: "#6aabf5",
    pillBg: "rgba(49,120,198,.12)",
    pillBorder: "rgba(49,120,198,.3)",
  },
  {
    name: "Tailwind",
    category: "Frontend",
    years: 3,
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/tailwindcss/tailwindcss-original.svg",
    color: "#38bdf8",
    shadow: "rgba(56,189,248,.22)",
    glow: "rgba(56,189,248,.13)",
    accent: "#7dd3fc",
    pillBg: "rgba(56,189,248,.12)",
    pillBorder: "rgba(56,189,248,.3)",
  },
  {
    name: "Framer",
    category: "Frontend",
    years: 2,
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/framermotion/framermotion-original.svg",
    color: "#a78bfa",
    shadow: "rgba(167,139,250,.22)",
    glow: "rgba(167,139,250,.13)",
    accent: "#c4b5fd",
    pillBg: "rgba(167,139,250,.12)",
    pillBorder: "rgba(167,139,250,.3)",
  },
  {
    name: "Node.js",
    category: "Backend",
    years: 4,
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg",
    color: "#6cc24a",
    shadow: "rgba(108,194,74,.22)",
    glow: "rgba(108,194,74,.13)",
    accent: "#86efac",
    pillBg: "rgba(108,194,74,.12)",
    pillBorder: "rgba(108,194,74,.3)",
  },
  {
    name: "PostgreSQL",
    category: "Backend",
    years: 3,
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg",
    color: "#336791",
    shadow: "rgba(51,103,145,.25)",
    glow: "rgba(51,103,145,.14)",
    accent: "#7eb8db",
    pillBg: "rgba(51,103,145,.12)",
    pillBorder: "rgba(51,103,145,.3)",
  },
  {
    name: "GraphQL",
    category: "Backend",
    years: 2,
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/graphql/graphql-plain.svg",
    color: "#e535ab",
    shadow: "rgba(229,53,171,.22)",
    glow: "rgba(229,53,171,.13)",
    accent: "#f0a3d9",
    pillBg: "rgba(229,53,171,.12)",
    pillBorder: "rgba(229,53,171,.3)",
  },
  {
    name: "Redis",
    category: "Backend",
    years: 2,
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redis/redis-original.svg",
    color: "#d82c20",
    shadow: "rgba(216,44,32,.22)",
    glow: "rgba(216,44,32,.13)",
    accent: "#fca5a5",
    pillBg: "rgba(216,44,32,.12)",
    pillBorder: "rgba(216,44,32,.3)",
  },
  {
    name: "Prisma",
    category: "Backend",
    years: 2,
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/prisma/prisma-original.svg",
    color: "rgba(255,255,255,.5)",
    shadow: "rgba(255,255,255,.1)",
    glow: "rgba(255,255,255,.07)",
    accent: "rgba(255,255,255,.7)",
    pillBg: "rgba(255,255,255,.07)",
    pillBorder: "rgba(255,255,255,.2)",
  },

  {
    name: "Figma",
    category: "Design",
    years: 4,
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/figma/figma-original.svg",
    color: "#a259ff",
    shadow: "rgba(162,89,255,.22)",
    glow: "rgba(162,89,255,.13)",
    accent: "#d8b4fe",
    pillBg: "rgba(162,89,255,.12)",
    pillBorder: "rgba(162,89,255,.3)",
  },
  {
    name: "Three.js",
    category: "Creative",
    years: 2,
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/threejs/threejs-original.svg",
    color: "rgba(255,255,255,.5)",
    shadow: "rgba(255,255,255,.1)",
    glow: "rgba(255,255,255,.07)",
    accent: "rgba(255,255,255,.7)",
    pillBg: "rgba(255,255,255,.07)",
    pillBorder: "rgba(255,255,255,.2)",
  },
  {
    name: "GSAP",
    category: "Creative",
    years: 2,
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/gsap/gsap-original.svg",
    color: "#88ce02",
    shadow: "rgba(136,206,2,.22)",
    glow: "rgba(136,206,2,.13)",
    accent: "#bef264",
    pillBg: "rgba(136,206,2,.12)",
    pillBorder: "rgba(136,206,2,.3)",
  },
  {
    name: "WebGL",
    category: "Creative",
    years: 1,
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/opengl/opengl-original.svg",
    color: "#5586a4",
    shadow: "rgba(85,134,164,.22)",
    glow: "rgba(85,134,164,.13)",
    accent: "#93c5fd",
    pillBg: "rgba(85,134,164,.12)",
    pillBorder: "rgba(85,134,164,.3)",
  },
];
